---
title: "Taxa de prisões por 100.000 habitantes"
author: "Raul de Sá Durlo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = F,
  comment = "#>",
  message = F,
  warning = F
)
```

##

```{r fig.width=10, fig.align='center', echo=FALSE}
# Pacotes ----------------------------------------------------------------------
library(tidyverse)
library(gganimate)
library(spcrimr)


# seleciona populacao-----------------------------------------------------------
pop <- seade %>% select(chave, municipio, ano, populacao)

# seleciona dados prisionais ---------------------------------------------------
prisoes <- 
  inner_join(pop, ssp_produtividade_policial,
             by = c("chave", "municipio", "ano")) %>%
  select(chave:ano,
         populacao,
         pessoas_presas_em_flagrante,
         pessoas_presas_por_mandado) %>%
  group_by(ano) %>%
  summarise_at(vars(populacao,
                    pessoas_presas_em_flagrante,
                    pessoas_presas_por_mandado), ~ sum(.)) %>%
  ungroup()



prisoes %>%
  transmute(ano = ano, 
            `Prisões em flagrante` = pessoas_presas_em_flagrante / populacao * 100000,
            `Prisões por mandato` = pessoas_presas_por_mandado / populacao * 100000) %>%
  gather(key = variavel, value = taxa, -ano, factor_key = T) %>%
  
  # começa ggplot ----------------------------------------------# 
  ggplot(aes(y = taxa, x = ano)) +
  # linhas -----------------------------------------------------#
  geom_line(aes(color=variavel), size=1.5) +
  # textos -----------------------------------------------------#
  labs(title = "",
       subtitle = "Estado de São Paulo",
       y = "Taxa por 100.000 hab.",
       x = "") +
  # escalas ----------------------------------------------------#
  scale_x_discrete(limits = seq(2002, 2017),
                   breaks = seq(2002, 2017),
                   labels = seq(2002, 2017)) +
  # temas ------------------------------------------------------#
  theme_light() +
  theme(axis.title = element_text(size = 13),
        axis.text = element_text(size = 12),
        plot.title = element_text(vjust = .5, hjust = .5, size = 17),
        plot.subtitle = element_text(vjust = .5, hjust = .5, size = 13),
        axis.text.x = element_text(angle = 45, hjust=1, vjust=1),
        legend.position = "bottom",
        legend.title = element_blank())
  # fim ggplot --------------------------------------------------#

```


## Código

```{r fig.width=10, fig.align='center', eval=FALSE}
# Pacotes ----------------------------------------------------------------------
library(tidyverse)
library(gganimate)
library(spcrimr)


# seleciona populacao-----------------------------------------------------------
pop <- seade %>% select(chave, municipio, ano, populacao)

# seleciona dados prisionais ---------------------------------------------------
prisoes <- 
  inner_join(pop, ssp_produtividade_policial,
             by = c("chave", "municipio", "ano")) %>%
  select(chave:ano,
         populacao,
         pessoas_presas_em_flagrante,
         pessoas_presas_por_mandado) %>%
  group_by(ano) %>%
  summarise_at(vars(populacao,
                    pessoas_presas_em_flagrante,
                    pessoas_presas_por_mandado), ~ sum(.)) %>%
  ungroup()



prisoes %>%
  transmute(ano = ano, 
            `Prisões em flagrante` = pessoas_presas_em_flagrante / populacao * 100000,
            `Prisões por mandato` = pessoas_presas_por_mandado / populacao * 100000) %>%
  gather(key = variavel, value = taxa, -ano, factor_key = T) %>%
  
  # começa ggplot ----------------------------------------------# 
  ggplot(aes(y = taxa, x = ano)) +
  # linhas -----------------------------------------------------#
  geom_line(aes(color=variavel), size=1.5) +
  # textos -----------------------------------------------------#
  labs(title = "Taxa de prisões por 100.000 habitantes",
       subtitle = "Estado de São Paulo",
       y = "Taxa por 100.000 hab.",
       x = "") +
  # escalas ----------------------------------------------------#
  scale_x_discrete(limits = seq(2002, 2017),
                   breaks = seq(2002, 2017),
                   labels = seq(2002, 2017)) +
  # temas ------------------------------------------------------#
  theme_bw() +
  theme(axis.title = element_text(size = 13),
        axis.text = element_text(size = 12),
        plot.title = element_text(vjust = .5, hjust = .5, size = 17),
        plot.subtitle = element_text(vjust = .5, hjust = .5, size = 13),
        axis.text.x = element_text(angle = 45, hjust=1, vjust=1),
        legend.position = "bottom",
        legend.title = element_blank())
  # fim ggplot --------------------------------------------------#

```

